### PR TITLE
Update to Mermaid version 9.3.0

### PR DESCRIPTION
**Pull request by apeacock1991**
Mermaid 9.3.0 is out, with lots of improvements, including title support for all diagrams!

Bumping the version here to 9.3.0 so it supports the latest and greatest Mermaid features. I think this is the only change required?

It will close https://github.com/mjbvz/vscode-markdown-mermaid/issues/164.

### CODE REVIEW

**Review by mjbvz — APPROVED** [review]

**Comment by mjbvz** [comment]
Thanks!

**Comment by apeacock1991** [comment]
@mjbvz is this released? The Marketplace looks updated, but when I installed the extension I'm not sure it picked up the new version... as when I generated an error, it still said Mermaid 9.2.2 🤔

**Comment by mjbvz** [comment]
Seems to work for me: 

Screenshot 2022-12-20 at 2 28 32 PM

Make sure to update to the latest extension version: 1.17.3

**Comment by crwdsmullz** [comment]
Yes it's showing Mermaid version 9.3.0, however this version also requires some new dependencies, which aren't imported. For example:
- Use of icons requires FontAwesome lib (missing)
- Use of `mindmap` graph type requires `mermaid-mindmap@9` lib (missing)

**Pull request merged**
