### PR TITLE
feat: mermaid zoom & pan

### LINKED ISSUE #125: zoom support
could you add zoom-in/out or page-width modify support?
sometimes the graph looks so small since limited by page width

### PR DESCRIPTION
**Pull request by typesafeui**
This PR adds support for panning and zooming in the mermaid MD preview window

Closes #125

### CODE REVIEW

**Comment by dsfrederic** [comment]
Please get this merged! Important feature for big diagrams

**Comment by jersuNF** [comment]
Can we get this pulled in?

**Comment by henrymgarrett** [comment]
We are waiting for this as well, can't read any of our diagrams anymore!

**Review by mjbvz — CHANGES_REQUESTED** [review]
Thanks for taking a look but this needs more thought and testing

Some initial things noticed from a quick test:

- The diagram now occupies more space. This is annoying for correctly sized diagrams

- You can end up zooming the diagram instead of scrolling. Maybe there should be an explicit button to start panning / zoom?

- Zoom/pan gets reset everytime the markdown is updated

- After zooming/panning you can end up with the diagram being cropped in weird ways

Screenshot 2024-04-30 at 3 08 30 PM

**Comment by mjbvz** [comment]
Closing because this hasn't seen recent activity and can't be merged in its current state

**Pull request closed without merging**
